### ISSUE TITLE
[Feature Request] Jobs category or 2 level categories 

### ISSUE THREAD

**Issue by kirantpatil** [rubytaiwan/jobs.ruby.tw#18]
Hello,

Please provide the jobs category field so that programmers can search based on the category as shown in jobs.37signals.com or better 2 level categories.

Example,
 Main Category       -> Sub Category
 Programming Jobs -> ruby, rails, android, sintara
 Design Jobs -> ruby, rails
 Miscellaneous Jobs -> ruby, rails
 Customer Service/Support Jobs -> ruby, rails

Thanks.

**Comment by JuanitoFatas** [comment]
Please send a pull request! Thank you.
