### ISSUE TITLE
i can't find config/database.yml.example file

### ISSUE THREAD

**Issue by yours2008** [rubytaiwan/jobs.ruby.tw#29]
so  i can't do cp config/database.yml.example config/database.yml

**Comment by okay44** [comment]
Maybe because it's being monitored

**Comment by ryudoawaru** [comment]
You can add it and send PR

**Comment by twocucao** [comment]
I cannot do this too
``` shell
cp config/database.yml.example config/database.yml
cp .....
```

is there any solution? 

or

just add an empty file, and do migrate with the command "rake db:migrate"??

**Comment by JuanitoFatas** [comment]
Done in #37.
