### ISSUE TITLE
BAD Request 問題

### ISSUE THREAD

**Issue by ryudoawaru** [rubytaiwan/jobs.ruby.tw#34]
An ActionController::BadRequest occurred in #:

ActionController::BadRequest

-------------------------------
Request:
-------------------------------

* URL : http://jobs.ruby.tw/jobs/156-%E9%9D%A2%E8%AB%871000%E8%A3%9C%E5%8A%A9%E7%9B%AE%E6%A8%99%E5%85%A8%E7%90%83%E5%B8%82%E5%A0%B4%E5%9C%96%E7%89%87%E5%88%86%E4%BA%AB%E7%A4%BE%E7%BE%A4%E7%B6%B2%E7%AB%99app%E5%8F%B0%E7%81%A3%E8%BE%A6%E5%85%AC%E5%AE%A4%E8%AA%A0%E5
* HTTP Method: GET
* IP address : 195.154.211.220
* Parameters : {"controller"=>"jobs", "action"=>"show", "id"=>"156-面談1000補助目標全球市場圖片分享社群網站app台灣辦公室誠\xE5"}
* Timestamp : 2015-05-13 08:53:24 +0800
* Server : rubytw
* Rails root : /var/Data/deployhome/jobs.ruby.tw/releases/20150302095614
* Process: 28546

-------------------------------
Session:
-------------------------------

* session id: nil
* data: #<ActionDispatch::Request::Session:0x7fcc3dd83f68 not yet loaded>

-------------------------------
Environment:
-------------------------------

* DOCUMENT_ROOT : /home/deploy/jobs.ruby.tw/current/public
* HTTP_ACCEPT : text/html,application/xhtml+xml,application/xml
* HTTP_CONNECTION : close
* HTTP_HOST : jobs.ruby.tw
* HTTP_USER_AGENT : Mozilla/5.0 (Windows NT 6.2; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
* ORIGINAL_FULLPATH : /jobs/156-%e9%9d%a2%e8%ab%871000%e8%a3%9c%e5%8a%a9%e7%9b%ae%e6%a8%99%e5%85%a8%e7%90%83%e5%b8%82%e5%a0%b4%e5%9c%96%e7%89%87%e5%88%86%e4%ba%ab%e7%a4%be%e7%be%a4%e7%b6%b2%e7%ab%99app%e5%8f%b0%e7%81%a3%e8%be%a6%e5%85%ac%e5%ae%a4%e8%aa%a0%e5
* ORIGINAL_SCRIPT_NAME :
* PASSENGER_APP_ENV : production
* PASSENGER_APP_TYPE : rack
* PASSENGER_CONNECT_PASSWORD : [FILTERED]
* PATH_INFO : /jobs/156-%E9%9D%A2%E8%AB%871000%E8%A3%9C%E5%8A%A9%E7%9B%AE%E6%A8%99%E5%85%A8%E7%90%83%E5%B8%82%E5%A0%B4%E5%9C%96%E7%89%87%E5%88%86%E4%BA%AB%E7%A4%BE%E7%BE%A4%E7%B6%B2%E7%AB%99app%E5%8F%B0%E7%81%A3%E8%BE%A6%E5%85%AC%E5%AE%A4%E8%AA%A0%E5
* QUERY_STRING :
* REMOTE_ADDR : 195.154.211.220
* REMOTE_PORT : 52067
* REQUEST_METHOD : GET
* REQUEST_URI : /jobs/156-%e9%9d%a2%e8%ab%871000%e8%a3%9c%e5%8a%a9%e7%9b%ae%e6%a8%99%e5%85%a8%e7%90%83%e5%b8%82%e5%a0%b4%e5%9c%96%e7%89%87%e5%88%86%e4%ba%ab%e7%a4%be%e7%be%a4%e7%b6%b2%e7%ab%99app%e5%8f%b0%e7%81%a3%e8%be%a6%e5%85%ac%e5%ae%a4%e8%aa%a0%e5
* ROUTES_70257792147380_SCRIPT_NAME :
* SCGI : 1
* SCRIPT_NAME :
* SERVER_ADDR : 100.79.158.86
* SERVER_NAME : jobs.ruby.tw
* SERVER_PORT : 80
* SERVER_PROTOCOL : HTTP/1.1
* SERVER_SOFTWARE : nginx/1.6.2
* action_dispatch.backtrace_cleaner : #<Rails::BacktraceCleaner:0x007fcc53f9af70>
* action_dispatch.cookies : #<ActionDispatch::Cookies::CookieJar:0x007fcc3d3e1848>
* action_dispatch.cookies_digest :
* action_dispatch.cookies_serializer : marshal
* action_dispatch.encrypted_cookie_salt : encrypted cookie
* action_dispatch.encrypted_signed_cookie_salt : signed encrypted cookie
* action_dispatch.http_auth_salt : http authentication
* action_dispatch.key_generator : #<ActiveSupport::CachingKeyGenerator:0x007fcc56f7c478>
* action_dispatch.logger : #<ActiveSupport::Logger:0x007fcc5562ad08>
* action_dispatch.parameter_filter : [:password]
* action_dispatch.redirect_filter : []
* action_dispatch.remote_ip : 195.154.211.220
* action_dispatch.request.content_type :
* action_dispatch.request.parameters : {"controller"=>"jobs", "action"=>"show", "id"=>"156-面談1000補助目標全球市場圖片分享社群網站app台灣辦公室誠\xE5"}
* action_dispatch.request.path_parameters : {:controller=>"jobs", :action=>"show", :id=>"156-面談1000補助目標全球市場圖片分享社群網站app台灣辦公室誠\xE5"}
* action_dispatch.request.query_parameters : {}
* action_dispatch.request.request_parameters : {}
* action_dispatch.request.unsigned_session_cookie: {}
* action_dispatch.request_id : 803d7812-1b75-4fb5-8930-669c4ce76154
* action_dispatch.routes : #<ActionDispatch::Routing::RouteSet:0x007fcc557cbf68>

* action_dispatch.secret_token :
* action_dispatch.show_detailed_exceptions : false
* action_dispatch.show_exceptions : true
* action_dispatch.signed_cookie_salt : signed cookie
* rack.errors : #<IO:0x007fcc53705540>
* rack.hijack : #<Proc:0x007fcc3ce94d18@/usr/local/ruby22/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/rack/thread_handler_extension.rb:69 (lambda)>
* rack.hijack? : true
* rack.input : #<PhusionPassenger::Utils::TeeInput:0x007fcc3ce94ef8>
* rack.multiprocess : true
* rack.multithread : false
* rack.request.cookie_hash : {}
* rack.request.query_hash : {}
* rack.request.query_string :
* rack.run_once : false
* rack.session : #<ActionDispatch::Request::Session:0x007fcc3dd83f68>
* rack.session.options : #<ActionDispatch::Request::Session::Options:0x007fcc3dd83f18>
* rack.url_scheme : http
* rack.version : [1, 2]
* warden : Warden::Proxy:70257593818940 @config={:default_scope=>:user, :scope_defaults=>{}, :default_strategies=>{:user=>[:rememberable, :database_authenticatable]}, :intercept_401=>false, :failure_app=>#<Devise::Delegator:0x007fcc57052708>}

**Comment by ryudoawaru** [comment]
utf8-cleaner  gem 應該可解決此問題

**Comment by JuanitoFatas** [comment]
Already been fixed.
