### ISSUE TITLE
Missing Template 問題

### ISSUE THREAD

**Issue by ryudoawaru** [rubytaiwan/jobs.ruby.tw#35]
An ActionView::MissingTemplate occurred in jobs#show:

Missing template pages/404 with {:locale=>[:zh_tw, :en], :formats=>[:mobile], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee]}. Searched in:
* "/var/Data/deployhome/jobs.ruby.tw/releases/20150302095614/app/views"
* "/var/Data/deployhome/jobs.ruby.tw/shared/bundle/ruby/2.2.0/gems/devise-3.4.1/app/views"

app/controllers/application_controller.rb:22:in `render_not_found'

-------------------------------
Request:
-------------------------------

* URL : http://jobs.ruby.tw/jobs/247-%E7%A8%8B%E5%BC%8F%E8%A8%AD%E8%A8%88%E5%B8%AB-%E5%8F%B0%E7%81%A3%E9%86%92%E5%A0%B1?locale=zh_tw
* HTTP Method: GET
* IP address : 66.249.79.98
* Parameters : {"locale"=>"zh_tw", "controller"=>"jobs", "action"=>"show", "id"=>"247-程式設計師-台灣醒報", "format"=>"mobile"}
* Timestamp : 2015-05-13 04:56:08 +0800
* Server : rubytw
* Rails root : /var/Data/deployhome/jobs.ruby.tw/releases/20150302095614
* Process: 28546

-------------------------------
Session:
-------------------------------

* session id: "659b3198381bb0e22cc82993935e6051"
* data: #<ActionDispatch::Request::Session:0x007fcc3de58560 ...>

-------------------------------
Environment:
-------------------------------

* DOCUMENT_ROOT : /home/deploy/jobs.ruby.tw/current/public
* HTTP_ACCEPT : text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
* HTTP_ACCEPT_ENCODING : gzip,deflate
* HTTP_CONNECTION : Keep-alive
* HTTP_FROM : googlebot(at)googlebot.com
* HTTP_HOST : jobs.ruby.tw
* HTTP_USER_AGENT : Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
* ORIGINAL_FULLPATH : /jobs/247-%e7%a8%8b%e5%bc%8f%e8%a8%ad%e8%a8%88%e5%b8%ab-%e5%8f%b0%e7%81%a3%e9%86%92%e5%a0%b1?locale=zh_tw
* ORIGINAL_SCRIPT_NAME :
* PASSENGER_APP_ENV : production
* PASSENGER_APP_TYPE : rack
* PASSENGER_CONNECT_PASSWORD : [FILTERED]
* PATH_INFO : /jobs/247-%E7%A8%8B%E5%BC%8F%E8%A8%AD%E8%A8%88%E5%B8%AB-%E5%8F%B0%E7%81%A3%E9%86%92%E5%A0%B1
* QUERY_STRING : locale=zh_tw
* REMOTE_ADDR : 66.249.79.98
* REMOTE_PORT : 40328
* REQUEST_METHOD : GET
* REQUEST_URI : /jobs/247-%e7%a8%8b%e5%bc%8f%e8%a8%ad%e8%a8%88%e5%b8%ab-%e5%8f%b0%e7%81%a3%e9%86%92%e5%a0%b1?locale=zh_tw
* ROUTES_70257792147380_SCRIPT_NAME :
* SCGI : 1
* SCRIPT_NAME :
* SERVER_ADDR : 100.79.158.86
* SERVER_NAME : jobs.ruby.tw
* SERVER_PORT : 80
* SERVER_PROTOCOL : HTTP/1.1
* SERVER_SOFTWARE : nginx/1.6.2
* X_MOBILE_DEVICE : iPhone
* action_controller.instance : #<JobsController:0x007fcc3d284310>
* action_dispatch.backtrace_cleaner : #<Rails::BacktraceCleaner:0x007fcc53f9af70>
* action_dispatch.cookies : #<ActionDispatch::Cookies::CookieJar:0x007fcc3e5419d0>
* action_dispatch.cookies_digest :
* action_dispatch.cookies_serializer : marshal
* action_dispatch.encrypted_cookie_salt : encrypted cookie
* action_dispatch.encrypted_signed_cookie_salt : signed encrypted cookie
* action_dispatch.http_auth_salt : http authentication
* action_dispatch.key_generator : #<ActiveSupport::CachingKeyGenerator:0x007fcc56f7c478>
* action_dispatch.logger : #<ActiveSupport::Logger:0x007fcc5562ad08>
* action_dispatch.parameter_filter : [:password]
* action_dispatch.redirect_filter : []
* action_dispatch.remote_ip : 66.249.79.98
* action_dispatch.request.content_type :
* action_dispatch.request.formats : [#<Mime::Type:0x007fcc5593df40 @synonyms=[], @symbol=:mobile, @string="text/html">]
* action_dispatch.request.parameters : {"locale"=>"zh_tw", "controller"=>"jobs", "action"=>"show", "id"=>"247-程式設計師-台灣醒報", "format"=>"mobile"}
* action_dispatch.request.path_parameters : {:controller=>"jobs", :action=>"show", :id=>"247-程式設計師-台灣醒報"}
* action_dispatch.request.query_parameters : {"locale"=>"zh_tw"}
* action_dispatch.request.request_parameters : {}
* action_dispatch.request.unsigned_session_cookie: {"session_id"=>"659b3198381bb0e22cc82993935e6051"}
* action_dispatch.request_id : 0c554894-d73d-4b81-937b-f6d177137e54
* action_dispatch.routes : #<ActionDispatch::Routing::RouteSet:0x007fcc557cbf68>
* action_dispatch.secret_key_base : xxx
* action_dispatch.secret_token :
* action_dispatch.show_detailed_exceptions : false
* action_dispatch.show_exceptions : true
* action_dispatch.signed_cookie_salt : signed cookie
* rack.errors : #<IO:0x007fcc53705540>
* rack.hijack : #<Proc:0x007fcc3de597d0@/usr/local/ruby22/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/rack/thread_handler_extension.rb:69 (lambda)>
* rack.hijack? : true
* rack.input : #<PhusionPassenger::Utils::TeeInput:0x007fcc3de599b0>
* rack.multiprocess : true
* rack.multithread : false
* rack.request.cookie_hash : {}
* rack.request.query_hash : {"locale"=>"zh_tw"}
* rack.request.query_string : locale=zh_tw
* rack.run_once : false
* rack.session : #<ActionDispatch::Request::Session:0x007fcc3de58560>
* rack.session.options : #<ActionDispatch::Request::Session::Options:0x007fcc3de58510>
* rack.url_scheme : http
* rack.version : [1, 2]
* warden : Warden::Proxy:70257594253880 @config={:default_scope=>:user, :scope_defaults=>{}, :default_strategies=>{:user=>[:rememberable, :database_authenticatable]}, :intercept_401=>false, :failure_app=>#<Devise::Delegator:0x007fcc57052708>}

-------------------------------
Backtrace:
-------------------------------

app/controllers/application_controller.rb:22:in `render_not_found'

**Comment by JuanitoFatas** [comment]
Already been fixed.
