### ISSUE TITLE
Post to Slack when a new job has been created

### ISSUE THREAD

**Issue by JuanitoFatas** [rubytaiwan/jobs.ruby.tw#47]
Use https://github.com/httprb/http for making requests. :zap: 
The format can reference [message attachments](https://api.slack.com/docs/attachments). :heart_eyes: 
With specs of course. :wink: 
DM me for Slack credentials. :speak_no_evil: 

Anyone feel free to tackle this, thanks! :+1:

**Comment by puff-tw** [comment]
The other way is subscribe this rss in slack.
http://feeds.feedburner.com/rubyjobs-taiwan

May be you have more data source?

**Comment by JuanitoFatas** [comment]
Was adding this issue as a way to mentor someone :wink: 

> May be you have more data source?

RSS seems good! Subscribe to slack channel then. Thanks @puff-tw !
